### PR TITLE
Fixing\Updating AzsAdmin Compute powershell generation and tests.

### PR DESCRIPTION
**Pull request by travist13**
**Open API spec PR is updated and merged.**
Dependent Open API Spec PR: https://github.com/Azure/azure-rest-api-specs/pull/15059

This fixes many of the issues with the module generation and the tests. I also added a test for the new computeScaleUnit API.

### CODE REVIEW

**Comment by TheOnlyWei** [comment]
There are tests that have not been implemented, will these be implemented in the future?

**Comment by travist13** [comment]
> There are tests that have not been implemented, will these be implemented in the future?

The "Feature" tests are being implemented by Miguel. For the other NotImplemented tests I will create work items to implement those in a later effort. However, these other APIs are not changed recently and are being covered in our nightly team CI runs.

**Comment by bganapa** [comment]
@travist13 closing this PR as your other PR is merged.

**Pull request closed without merging**
