### PR TITLE
Removing the preview warning in AzureStack module and updating release notes

### PR DESCRIPTION
**Pull request by bganapa**

### CODE REVIEW

**Comment by TheOnlyWei** [comment]
Minor: misspelled "updating" in commit message.

**Comment by bganapa** [comment]
> Minor: misspelled "updating" in commit message.

Change it in the PR title

**Comment by TheOnlyWei** [comment]
> > Minor: misspelled "updating" in commit message.
> 
> Changed it in the PR title

It is also in your commit message since the title takes it from there.

**Review by TheOnlyWei — APPROVED** [review]

**Comment by bganapa** [comment]
> It is also in your commit message since the title takes it from there.

fixed the commit message as well

**Pull request merged**
