### PR TITLE
AzureStack Update Powershell for API2021-07-01

### PR DESCRIPTION
**Pull request by LingyunSu**
AzureStack Update Powershell for new API

### CODE REVIEW

**Review by alexbass112 — DISMISSED** [review]

**Comment by TheOnlyWei** [comment]
Hi @LingyunSu, can you go through this code review checklist:
https://github.com/Azure/azurestack-powershell/wiki/Code-Review-Check-List

**Comment by TheOnlyWei** [comment]
Hi @LingyunSu Can you squash the unnecessary commits in git to track this feature as a single commit with a meaningful message?

**Pull request closed without merging**
