### PR TITLE
Enable GPU in Fabric.Admin 

### PR DESCRIPTION
**Pull request by LingyunSu**
Enable GPU in Fabric.Admin

### CODE REVIEW

**Comment by bganapa** [comment]
@TheOnlyWei could you pls see why the tests are failing

**Comment by TheOnlyWei** [comment]
I ran the test pipeline manually and the pipeline succeeded: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=601623&view=results

**Comment by bganapa** [comment]
@TheOnlyWei were you able to see why the tests are failing in this PR?

**Comment by TheOnlyWei** [comment]
@bganapa There is a new error now, that the previous builds create files that causes newer builds to fail because last build's files exist, that causes conflict with newer builds. I added delete files task before publishing task to see if it fixes it.

**Comment by TheOnlyWei** [comment]
@LingyunSu Can you edit the commit with something small and force push to re-run the tests? Re-run the current pipeline checks doesn't pick up new pipeline changes for some reason.

**Comment by TheOnlyWei** [comment]
@LingyunSu AzureDevops limitation means generated artifacts cannot be deleted in new runs of the same pipeline. This causes conflicts when Github tries to re-run the same pipeline due to file name conflict. You will have to re-run this PR with a new pipeline with no artifacts by making a minor change to your commit, e.g. changing commit message, and then force pushing the change to kick off a new pipeline.

**Comment by bganapa** [comment]
@TheOnlyWei can you pls add a work item to make the azure dev ops pipeline reentrant. We should be able to rerun without issues.  @LingyunSu I hope you are still making changes for this PR

**Review by TheOnlyWei — APPROVED** [review]

**Pull request merged**
