### PR TITLE
change rest api branch from stackadmin2 to master

### PR DESCRIPTION
**Pull request by TheOnlyWei**
change rest api branch from stackadmin2 to master

### CODE REVIEW

**Comment by bganapa** [comment]
Lets wait to merge till we release AzureStack 2.1.1

**Review by travist13 — DISMISSED** [review]
Looks good.

**Comment by bganapa** [comment]
> Looks good.

Thanks @travist13  for the approval. I see that the tests need to be re-recorded for the changes. We will take them part of your PR.  FOr now,  This PR will unblock us to move to consuming main branch instead of stackadmin2

**Review by bganapa — APPROVED** [review]

**Pull request merged**
