### PR TITLE
Changes for tests to run in test pipeline

### PR DESCRIPTION
**Pull request by viananth**

### CODE REVIEW

**Comment by TheOnlyWei** [comment]
Bala suggested moving $envFile from the tests to the common.ps1 file, but I tried that by adding $global:envFile to the common.ps1 file but that started throwing errors that does not seem to be related to the variable change and so would have been difficult to debug, so I put it back in my PR. What are your thoughts?

**Comment by viananth** [comment]
> Bala suggested moving $envFile from the tests to the common.ps1 file, but I tried that by adding $global:envFile to the common.ps1 file but that started throwing errors that does not seem to be related to the variable change and so would have been difficult to debug, so I put it back in my PR. What are your thoughts?

@TheOnlyWei Xiaogang suggested this work around for the above issue:

> If you need to add a default parameter, you should do it in the setEnv function in utils.ps1.
 
You may refer to https://github.com/Azure/azure-powershell/blob/generation/src/Databricks/test/utils.ps1 as an example.

**Comment by bganapa** [comment]
@viananth could you please merge this? you should have permissions, prefer Rebase and Merge option

**Comment by viananth** [comment]
Tests passed. Pipeline failed at publish artifact step. Merging now.

**Pull request merged**
